<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="LAPTOP-E2PSIL5I" failures="1" tests="2" name="Test_Login" time="75.841" errors="0" timestamp="2023-11-07T14:41:52 IST">
  <testcase classname="MyAccount.Tests.LoginTest" name="loginTest" time="0.055">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at MyAccount.Tests.LoginTest.loginTest(LoginTest.java:20)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="MyAccount.Tests.LogOutTest" name="logOutTest" time="39.063"/>
  <testcase classname="genericUtilities.BaseClass_new" name="@BeforeSuite createExtentReport_bsConfig" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite createExtentReport_bsConfig -->
  <testcase classname="genericUtilities.BaseClass_new" name="@AfterSuite flushExtentReport_asConfig" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite flushExtentReport_asConfig -->
</testsuite> <!-- Test_Login -->
